package com.zhouwj.recognition.entity;

import java.util.Date;

public class Carinf {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carinf.carinf_carnum
     *
     * @mbggenerated Wed Mar 27 10:10:45 CST 2019
     */
    private String carinfCarnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carinf.carinf_userid
     *
     * @mbggenerated Wed Mar 27 10:10:45 CST 2019
     */
    private Integer carinfUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carinf.carinf_cardis
     *
     * @mbggenerated Wed Mar 27 10:10:45 CST 2019
     */
    private String carinfCardis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carinf.carinf_time
     *
     * @mbggenerated Wed Mar 27 10:10:45 CST 2019
     */
    private Date carinfTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carinf.carinf_carnum
     *
     * @return the value of carinf.carinf_carnum
     *
     * @mbggenerated Wed Mar 27 10:10:45 CST 2019
     */
    public String getCarinfCarnum() {
        return carinfCarnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carinf.carinf_carnum
     *
     * @param carinfCarnum the value for carinf.carinf_carnum
     *
     * @mbggenerated Wed Mar 27 10:10:45 CST 2019
     */
    public void setCarinfCarnum(String carinfCarnum) {
        this.carinfCarnum = carinfCarnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carinf.carinf_userid
     *
     * @return the value of carinf.carinf_userid
     *
     * @mbggenerated Wed Mar 27 10:10:45 CST 2019
     */
    public Integer getCarinfUserid() {
        return carinfUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carinf.carinf_userid
     *
     * @param carinfUserid the value for carinf.carinf_userid
     *
     * @mbggenerated Wed Mar 27 10:10:45 CST 2019
     */
    public void setCarinfUserid(Integer carinfUserid) {
        this.carinfUserid = carinfUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carinf.carinf_cardis
     *
     * @return the value of carinf.carinf_cardis
     *
     * @mbggenerated Wed Mar 27 10:10:45 CST 2019
     */
    public String getCarinfCardis() {
        return carinfCardis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carinf.carinf_cardis
     *
     * @param carinfCardis the value for carinf.carinf_cardis
     *
     * @mbggenerated Wed Mar 27 10:10:45 CST 2019
     */
    public void setCarinfCardis(String carinfCardis) {
        this.carinfCardis = carinfCardis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carinf.carinf_time
     *
     * @return the value of carinf.carinf_time
     *
     * @mbggenerated Wed Mar 27 10:10:45 CST 2019
     */
    public Date getCarinfTime() {
        return carinfTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carinf.carinf_time
     *
     * @param carinfTime the value for carinf.carinf_time
     *
     * @mbggenerated Wed Mar 27 10:10:45 CST 2019
     */
    public void setCarinfTime(Date carinfTime) {
        this.carinfTime = carinfTime;
    }
}