package com.zhouwj.recognition.entity;

public class Cit {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cit.cit_carnum
     *
     * @mbggenerated Wed Mar 27 10:11:34 CST 2019
     */
    private String citCarnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cit.cit_owner
     *
     * @mbggenerated Wed Mar 27 10:11:34 CST 2019
     */
    private String citOwner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cit.cit_phonenum
     *
     * @mbggenerated Wed Mar 27 10:11:34 CST 2019
     */
    private String citPhonenum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cit.cit_carnum
     *
     * @return the value of cit.cit_carnum
     *
     * @mbggenerated Wed Mar 27 10:11:34 CST 2019
     */
    public String getCitCarnum() {
        return citCarnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cit.cit_carnum
     *
     * @param citCarnum the value for cit.cit_carnum
     *
     * @mbggenerated Wed Mar 27 10:11:34 CST 2019
     */
    public void setCitCarnum(String citCarnum) {
        this.citCarnum = citCarnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cit.cit_owner
     *
     * @return the value of cit.cit_owner
     *
     * @mbggenerated Wed Mar 27 10:11:34 CST 2019
     */
    public String getCitOwner() {
        return citOwner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cit.cit_owner
     *
     * @param citOwner the value for cit.cit_owner
     *
     * @mbggenerated Wed Mar 27 10:11:34 CST 2019
     */
    public void setCitOwner(String citOwner) {
        this.citOwner = citOwner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cit.cit_phonenum
     *
     * @return the value of cit.cit_phonenum
     *
     * @mbggenerated Wed Mar 27 10:11:34 CST 2019
     */
    public String getCitPhonenum() {
        return citPhonenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cit.cit_phonenum
     *
     * @param citPhonenum the value for cit.cit_phonenum
     *
     * @mbggenerated Wed Mar 27 10:11:34 CST 2019
     */
    public void setCitPhonenum(String citPhonenum) {
        this.citPhonenum = citPhonenum;
    }
}