package com.zhouwj.recognition.entity;

public class NetUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column netuser.username
     *
     * @mbggenerated Wed Mar 27 10:12:09 CST 2019
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column netuser.password
     *
     * @mbggenerated Wed Mar 27 10:12:09 CST 2019
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column netuser.username
     *
     * @return the value of netuser.username
     *
     * @mbggenerated Wed Mar 27 10:12:09 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column netuser.username
     *
     * @param username the value for netuser.username
     *
     * @mbggenerated Wed Mar 27 10:12:09 CST 2019
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column netuser.password
     *
     * @return the value of netuser.password
     *
     * @mbggenerated Wed Mar 27 10:12:09 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column netuser.password
     *
     * @param password the value for netuser.password
     *
     * @mbggenerated Wed Mar 27 10:12:09 CST 2019
     */
    public void setPassword(String password) {
        this.password = password;
    }
}