package com.zhouwj.recognition.entity;

public class Users {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_id
     *
     * @mbggenerated Wed Mar 27 09:28:11 CST 2019
     */
    private Integer usersId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_name
     *
     * @mbggenerated Wed Mar 27 09:28:11 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_password
     *
     * @mbggenerated Wed Mar 27 09:28:11 CST 2019
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_id
     *
     * @return the value of users.users_id
     *
     * @mbggenerated Wed Mar 27 09:28:11 CST 2019
     */
    public Integer getUsersId() {
        return usersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_id
     *
     * @param usersId the value for users.users_id
     *
     * @mbggenerated Wed Mar 27 09:28:11 CST 2019
     */
    public void setUsersId(Integer usersId) {
        this.usersId = usersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_name
     *
     * @return the value of users.users_name
     *
     * @mbggenerated Wed Mar 27 09:28:11 CST 2019
     */
    public String getName() {
        return name;
    }

    public Users (String name,String password){
        this.name=name;
        this.password=password;
    }

    public Users(){super();}

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_name
     *
     * @param name the value for users.users_name
     *
     * @mbggenerated Wed Mar 27 09:28:11 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_password
     *
     * @return the value of users.users_password
     *
     * @mbggenerated Wed Mar 27 09:28:11 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_password
     *
     * @param password the value for users.users_password
     *
     * @mbggenerated Wed Mar 27 09:28:11 CST 2019
     */
    public void setPassword(String password) {
        this.password = password;
    }
}