package com.zhouwj.recognition.mapper;

import com.zhouwj.recognition.entity.Carinf;

public interface CarinfMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carinf
     *
     * @mbggenerated Wed Mar 27 10:10:45 CST 2019
     */
    int insert(Carinf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carinf
     *
     * @mbggenerated Wed Mar 27 10:10:45 CST 2019
     */
    int insertSelective(Carinf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carinf
     *
     * @mbggenerated Wed Mar 27 10:10:45 CST 2019
     */
    Carinf selectByPrimaryKey(String carinfCarnum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carinf
     *
     * @mbggenerated Wed Mar 27 10:10:45 CST 2019
     */
    int updateByPrimaryKeySelective(Carinf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carinf
     *
     * @mbggenerated Wed Mar 27 10:10:45 CST 2019
     */
    int updateByPrimaryKey(Carinf record);

    Carinf deleteCarInfo(String carnum);
}