package com.zhouwj.recognition.mapper;

import com.zhouwj.recognition.entity.Users;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UsersMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Wed Mar 27 09:28:11 CST 2019
     */
    int deleteByPrimaryKey(Integer usersId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Wed Mar 27 09:28:11 CST 2019
     */
    int insert(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Wed Mar 27 09:28:11 CST 2019
     */
    int insertSelective(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Wed Mar 27 09:28:11 CST 2019
     */
    Users selectByPrimaryKey(Integer usersId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Wed Mar 27 09:28:11 CST 2019
     */
    int updateByPrimaryKeySelective(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Wed Mar 27 09:28:11 CST 2019
     */
    int updateByPrimaryKey(Users record);

}